import { CinematicAct, CinematicShot, FeatureFilmDialogue } from "./dharmakshetra15m";

export const NAPOLEON_ROMANCE_ACTS: CinematicAct[] = [
  {
    actNumber: 1,
    title: "The Fires of Youth & The Unsent Letters",
    tagline: "Marseilles & Paris 1795–1797 · Désirée Clary & The First Encounter with Joséphine (00:00 - 00:36)",
    timecodeStartSec: 0,
    timecodeEndSec: 36,
    durationSec: 36,
    shotRange: "Shots 001 - 006",
    musicalTheme: "Beethoven Symphony No. 7 in A major, Op. 92 – II. Allegretto (Movement I)",
    visualAtmosphere: "Marseille Coastline Terraces & Neoclassical Paris Candlelit Salons",
    dramaticStakes: "A young artillery officer torn between pure youthful devotion and intoxicating imperial destiny"
  },
  {
    actNumber: 2,
    title: "The Imperial Crown & The Rose Garden",
    tagline: "Notre-Dame & Malmaison 1804–1807 · Empress Joséphine Crowning & Sanctuary (00:36 - 01:12)",
    timecodeStartSec: 36,
    timecodeEndSec: 72,
    durationSec: 36,
    shotRange: "Shots 007 - 012",
    musicalTheme: "Beethoven Symphony No. 7 in A major, Op. 92 – II. Allegretto (Movement II)",
    visualAtmosphere: "Notre-Dame Gilded Imperial Sunlight & Rain-Drenched Malmaison Rose Arbors",
    dramaticStakes: "The pinnacle of empire where victory on the battlefield cannot cure the private ache of infertility"
  },
  {
    actNumber: 3,
    title: "The Polish Winter & Countess Walewska",
    tagline: "Finckenstein Castle 1807–1809 · Countess Marie Walewska & The Blizzard Refuge (01:12 - 01:48)",
    timecodeStartSec: 72,
    timecodeEndSec: 108,
    durationSec: 36,
    shotRange: "Shots 013 - 018",
    musicalTheme: "Beethoven Symphony No. 7 in A major, Op. 92 – II. Allegretto (Movement III)",
    visualAtmosphere: "Snow-Blown Prussian Pine Forests & Intimate Stone Fireplaces",
    dramaticStakes: "Passionate tenderness and loyalty discovered away from the politics of Paris"
  },
  {
    actNumber: 4,
    title: "The Dynastic Sacrifice & The King of Rome",
    tagline: "Tuileries & Vienna 1809–1811 · The Heartbreak of Divorce & Imperial Succession (01:48 - 02:24)",
    timecodeStartSec: 108,
    timecodeEndSec: 144,
    durationSec: 36,
    shotRange: "Shots 019 - 024",
    musicalTheme: "Beethoven Symphony No. 7 in A major, Op. 92 – II. Allegretto (Movement IV)",
    visualAtmosphere: "Shadowed Gilded Throne Rooms, Tear-Stained Decree Parchments, & Marble Nurseries",
    dramaticStakes: "Sacrificing genuine love for the imperial succession and dynastic duty"
  },
  {
    actNumber: 5,
    title: "The Solitary Echo & Saint Helena",
    tagline: "Longwood House 1814–1821 · The Final Whispers of Remembrance (02:24 - 03:00)",
    timecodeStartSec: 144,
    timecodeEndSec: 180,
    durationSec: 36,
    shotRange: "Shots 025 - 030",
    musicalTheme: "Beethoven Symphony No. 7 in A major, Op. 92 – II. Allegretto (Movement V Finale)",
    visualAtmosphere: "Wind-Whipped South Atlantic Cliffs, Fog-Choked French Windows, & Fading Candlelight",
    dramaticStakes: "The dying emperor reflects on the vanity of conquest and the eternity of love"
  }
];

export const NAPOLEON_ROMANCE_30_SHOTS: CinematicShot[] = [
  {
    shotNumber: 1,
    actNumber: 1,
    timecodeStartSec: 0,
    timecodeEndSec: 6,
    durationSec: 6,
    heading: "Marseille Coastline 1795",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Candlelight Neoclassical Chandelier",
    characters: ["Désirée Clary & Young Bonaparte"],
    actionDescription: "Cinematic 4K historical film shot of a young 18th-century French artillery officer in blue uniform standing on an old stone terrace in Marseille overlooking the Mediterranean Sea at sunset, speaking with a young French woman in provincial silk dress, 24fps photorealistic motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 2,
    actNumber: 1,
    timecodeStartSec: 6,
    timecodeEndSec: 12,
    durationSec: 6,
    heading: "Paris Salons 1795",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Rainy Tent Lantern & Rim Light",
    characters: ["First Encounter with Joséphine"],
    actionDescription: "Cinematic 4K historical drama shot inside an opulent candlelit Paris neoclassical salon 1795, young French general looking across the room at an elegant noblewoman with chestnut hair holding a feathered fan, chandeliers, 24fps smooth cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 3,
    actNumber: 1,
    timecodeStartSec: 12,
    timecodeEndSec: 18,
    durationSec: 6,
    heading: "Neoclassical Paris Courtyard",
    shotType: "Tracking Dolly",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Notre-Dame Golden Sunlight",
    characters: ["Joséphine de Beauharnais"],
    actionDescription: "Cinematic 4K medium shot of an elegant 18th-century French noblewoman with dark chestnut ringlets wearing high-waisted white muslin Empire gown and diamond earrings, laughing softly in a twilight courtyard, 24fps historical cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 4,
    actNumber: 1,
    timecodeStartSec: 18,
    timecodeEndSec: 24,
    durationSec: 6,
    heading: "Marriage Ceremony 1796",
    shotType: "Extreme Wide Aerial",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Finckenstein Fireplace Amber",
    characters: ["The Wedding Vow"],
    actionDescription: "Cinematic 4K close shot in a candlelit French registry hall 1796, hands exchanging a golden pocket watch engraved with the words Au Destin, white silk lace gloves, warm intimate lighting, 24fps macro cinematography",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 5,
    actNumber: 1,
    timecodeStartSec: 24,
    timecodeEndSec: 30,
    durationSec: 6,
    heading: "Italian Campaign Muddy Tent",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Longwood Atlantic Twilight Blue",
    characters: ["Napoleon Writing Love Letters"],
    actionDescription: "Cinematic 4K historical film shot inside a dark rainy military tent 1796, French general by lantern light passionately writing on parchment with a feather quill, heavy rain pouring outside, dramatic shadows, 24fps authentic motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 6,
    actNumber: 1,
    timecodeStartSec: 30,
    timecodeEndSec: 36,
    durationSec: 6,
    heading: "The Letter to Joséphine",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Sunset Amber Rim Light",
    characters: ["Parchment & Wax Seal"],
    actionDescription: "Cinematic 4K slow tracking shot across an antique French manuscript written in black ink with trembling cursive, red wax seal stamped with an imperial initial, melted candle wax, 24fps macro cinematic motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 7,
    actNumber: 2,
    timecodeStartSec: 36,
    timecodeEndSec: 42,
    durationSec: 6,
    heading: "Notre-Dame Coronation Ceremony",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Candlelight Neoclassical Chandelier",
    characters: ["Napoleon Crowning Joséphine"],
    actionDescription: "Cinematic 4K dynamic historical tracking shot inside Notre-Dame Cathedral Paris 1804, French emperor in crimson robe gently lowering a golden laurel crown above a kneeling neoclassical empress in white satin and diamond tiara, cathedral candles flickering, incense smoke drifting, slow continuous camera push-in, 24fps cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 8,
    actNumber: 2,
    timecodeStartSec: 42,
    timecodeEndSec: 48,
    durationSec: 6,
    heading: "Empress Joséphine Crowned",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Rainy Tent Lantern & Rim Light",
    characters: ["Joséphine Kneeling in Pride"],
    actionDescription: "Cinematic 4K medium close-up portrait of neoclassical French empress with proud emotional eyes wearing diamond tiara and crimson ermine mantle, subtle dignified breathing, soft cathedral backlight beams, regal composure, photorealistic 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 9,
    actNumber: 2,
    timecodeStartSec: 48,
    timecodeEndSec: 54,
    durationSec: 6,
    heading: "Château de Malmaison Greenhouse",
    shotType: "Tracking Dolly",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Notre-Dame Golden Sunlight",
    characters: ["The Empress's Rose Sanctuary"],
    actionDescription: "Cinematic 4K tracking shot through an antique 19th-century botanical glass conservatory filled with hundreds of blooming pink and white heritage French roses, soft morning sunlight, 24fps graceful camera glide",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 10,
    actNumber: 2,
    timecodeStartSec: 54,
    timecodeEndSec: 60,
    durationSec: 6,
    heading: "Joséphine Among the Roses",
    shotType: "Extreme Wide Aerial",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Finckenstein Fireplace Amber",
    characters: ["Joséphine Tending Flowers"],
    actionDescription: "Cinematic 4K wide tracking shot of an elegant 18th-century French noblewoman in flowing high-waisted white muslin Empire gown walking serenely through a sunlit botanical greenhouse filled with blooming pink heritage roses, soft morning breeze, graceful natural 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 11,
    actNumber: 2,
    timecodeStartSec: 60,
    timecodeEndSec: 66,
    durationSec: 6,
    heading: "Intimate Salon Dinner",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Longwood Atlantic Twilight Blue",
    characters: ["Napoleon & Joséphine at Malmaison"],
    actionDescription: "Cinematic 4K historical drama shot of French emperor in green chasseur uniform and empress seated at a candlelit mahogany dining table laughing intimately, silver candelabras, warm fireplace glow, 24fps cinematic drama",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 12,
    actNumber: 2,
    timecodeStartSec: 66,
    timecodeEndSec: 72,
    durationSec: 6,
    heading: "Whispered Promises",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Sunset Amber Rim Light",
    characters: ["The Royal Bedchamber"],
    actionDescription: "Cinematic 4K medium shot of imperial French couple holding hands beside a roaring hearth in an ornate gold-leaf French palace chamber, silk drapery, tender romantic atmosphere, 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 13,
    actNumber: 3,
    timecodeStartSec: 72,
    timecodeEndSec: 78,
    durationSec: 6,
    heading: "Warsaw Winter Crowds",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Candlelight Neoclassical Chandelier",
    characters: ["The Arrival in Poland"],
    actionDescription: "Cinematic 4K wide shot of an 1807 snowy Warsaw city street, French imperial black carriage surrounded by Polish nobility and cheering citizens in heavy winter fur coats under falling snow, 24fps period motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 14,
    actNumber: 3,
    timecodeStartSec: 78,
    timecodeEndSec: 84,
    durationSec: 6,
    heading: "Finckenstein Castle Blizzard",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Rainy Tent Lantern & Rim Light",
    characters: ["The Frozen Fortress"],
    actionDescription: "Cinematic 4K exterior cinematic shot of a Prussian gothic baroque brick castle at night during a swirling winter blizzard, glowing golden candlelight shining through arched windows, 24fps epic film cinematography",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 15,
    actNumber: 3,
    timecodeStartSec: 84,
    timecodeEndSec: 90,
    durationSec: 6,
    heading: "Countess Marie Walewska Entrance",
    shotType: "Tracking Dolly",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Notre-Dame Golden Sunlight",
    characters: ["Marie Walewska Entering Study"],
    actionDescription: "Cinematic 4K historical film shot of a beautiful young Polish countess with honey blonde hair wearing dark sapphire blue velvet winter coat trimmed with white fur entering a candlelit castle library, 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 16,
    actNumber: 3,
    timecodeStartSec: 90,
    timecodeEndSec: 96,
    durationSec: 6,
    heading: "Studying Maps by Firelight",
    shotType: "Extreme Wide Aerial",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Finckenstein Fireplace Amber",
    characters: ["Napoleon & Marie at the Table"],
    actionDescription: "Cinematic 4K medium shot of a French emperor in dark uniform leaning over large parchment maps on a wooden table with a young Polish noblewoman, roaring hearth fire casting warm amber light, 24fps drama",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 17,
    actNumber: 3,
    timecodeStartSec: 96,
    timecodeEndSec: 102,
    durationSec: 6,
    heading: "Tender Glance by the Hearth",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Longwood Atlantic Twilight Blue",
    characters: ["The Secret Polish Love"],
    actionDescription: "Cinematic 4K intimate close-up shot of French emperor smiling softly as Polish noblewoman speaks to him beside castle fireplace, crackling embers, soft cinematic depth of field, 24fps authentic cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 18,
    actNumber: 3,
    timecodeStartSec: 102,
    timecodeEndSec: 108,
    durationSec: 6,
    heading: "The Shadow Heir Alexandre",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Sunset Amber Rim Light",
    characters: ["The Polish Manor 1810"],
    actionDescription: "Cinematic 4K peaceful historical shot inside an elegant Polish country manor, blonde noblewoman gently rocking an antique wooden cradle wrapped in lace blankets, morning sunlight through lace curtains, 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 19,
    actNumber: 4,
    timecodeStartSec: 108,
    timecodeEndSec: 114,
    durationSec: 6,
    heading: "Tuileries Palace Confrontation",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Candlelight Neoclassical Chandelier",
    characters: ["The Impossible Choice"],
    actionDescription: "Cinematic 4K historical drama shot inside the Tuileries royal study, French emperor standing in profound sorrow facing his empress across a long council desk covered with state documents, 24fps tense drama",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 20,
    actNumber: 4,
    timecodeStartSec: 114,
    timecodeEndSec: 120,
    durationSec: 6,
    heading: "Signing the Divorce",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Rainy Tent Lantern & Rim Light",
    characters: ["Joséphine's Tears"],
    actionDescription: "Cinematic 4K historical drama medium shot of an elegant 18th-century neoclassical French empress seated at a mahogany desk in dark candlelit palace salon, head bowed in deep solemn contemplation, holding an antique feather quill over parchment document, dry face with dignified mournful expression, warm fireplace glow, natural real-time 24fps cinema velocity",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 21,
    actNumber: 4,
    timecodeStartSec: 120,
    timecodeEndSec: 126,
    durationSec: 6,
    heading: "The Solitary Departure",
    shotType: "Tracking Dolly",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Notre-Dame Golden Sunlight",
    characters: ["Napoleon in Grief"],
    actionDescription: "Cinematic 4K tracking shot of French emperor standing alone by tall palace windows watching a black royal carriage depart into the grey winter rain of Paris, head bowed, 24fps poignant motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 22,
    actNumber: 4,
    timecodeStartSec: 126,
    timecodeEndSec: 132,
    durationSec: 6,
    heading: "Louvre Wedding with Marie-Louise",
    shotType: "Extreme Wide Aerial",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Finckenstein Fireplace Amber",
    characters: ["The Austrian Habsburg Union"],
    actionDescription: "Cinematic 4K grand historical master shot inside the Louvre salon carre 1810, royal wedding between French emperor and young blonde Austrian archduchess in Habsburg golden brocade, clergy in robes, 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 23,
    actNumber: 4,
    timecodeStartSec: 132,
    timecodeEndSec: 138,
    durationSec: 6,
    heading: "Empress Marie-Louise Portrait",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Longwood Atlantic Twilight Blue",
    characters: ["The New Empress"],
    actionDescription: "Cinematic 4K portrait shot of a young Austrian imperial noblewoman with fair blonde hair and pearl necklace seated on a gilded French throne looking dignified yet distant, crystal chandeliers, 24fps cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 24,
    actNumber: 4,
    timecodeStartSec: 138,
    timecodeEndSec: 144,
    durationSec: 6,
    heading: "Birth of the King of Rome",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Sunset Amber Rim Light",
    characters: ["The Imperial Eagle Cradle"],
    actionDescription: "Cinematic 4K triumphant historical shot in Tuileries chamber 1811, French emperor joyfully lifting his newborn infant son wrapped in golden embroidered silk above an ornate golden eagle cradle, 24fps cinematic motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 25,
    actNumber: 5,
    timecodeStartSec: 144,
    timecodeEndSec: 150,
    durationSec: 6,
    heading: "Joséphine's Passing at Malmaison",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Candlelight Neoclassical Chandelier",
    characters: ["The Deathbed of Joséphine 1814"],
    actionDescription: "Cinematic 4K solemn historical shot inside Château de Malmaison bedroom 1814, empty four-poster swan bed adorned with pink rose petals, soft rain against French windows, melancholy atmosphere, 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 26,
    actNumber: 5,
    timecodeStartSec: 150,
    timecodeEndSec: 156,
    durationSec: 6,
    heading: "Napoleon at Malmaison Alone",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Rainy Tent Lantern & Rim Light",
    characters: ["Touching Her Empty Chair"],
    actionDescription: "Cinematic 4K dramatic shot of French emperor in grey overcoat walking slowly through the silent salons of Malmaison, touching an empty embroidered armchair with trembling hand, 24fps poignant cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 27,
    actNumber: 5,
    timecodeStartSec: 156,
    timecodeEndSec: 162,
    durationSec: 6,
    heading: "Vienna Schönbrunn Palace",
    shotType: "Tracking Dolly",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Angenieux Optimo 40-120mm",
    lighting: "Notre-Dame Golden Sunlight",
    characters: ["The Separated Son"],
    actionDescription: "Cinematic 4K historical shot in Austrian palace garden 1816, blonde young prince in white Austrian military tunic looking out from palace gates, separated from his father, 24fps cinematic motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 28,
    actNumber: 5,
    timecodeStartSec: 162,
    timecodeEndSec: 168,
    durationSec: 6,
    heading: "Saint Helena Longwood Study",
    shotType: "Extreme Wide Aerial",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Panavision Primo 35mm T1.4",
    lighting: "Finckenstein Fireplace Amber",
    characters: ["The Miniature Portrait"],
    actionDescription: "Cinematic 4K close shot in a dim colonial room on Saint Helena island, weathered hands of exiled emperor holding a tiny oval golden medallion containing the painted portrait of Empress Joséphine, 24fps cinema",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 29,
    actNumber: 5,
    timecodeStartSec: 168,
    timecodeEndSec: 174,
    durationSec: 6,
    heading: "Atlantic Cliffs at Twilight",
    shotType: "Close-Up Hero",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Cooke Anamorphic 50mm T2.3",
    lighting: "Longwood Atlantic Twilight Blue",
    characters: ["The Ocean Exile"],
    actionDescription: "Cinematic 4K wide shot of an exiled general in bicorne hat standing solitary on high black volcanic cliffs of Saint Helena island, stormy Atlantic ocean waves crashing below, sunset breaking clouds, 24fps motion",
    soundCue: "Chamber Cello & Foley"
  },
  {
    shotNumber: 30,
    actNumber: 5,
    timecodeStartSec: 174,
    timecodeEndSec: 180,
    durationSec: 6,
    heading: "The Dying Whisper 1821",
    shotType: "Medium Two-Shot",
    cameraMotion: "Slow Cinematic Push-In (24fps)",
    lens: "Zeiss Master Prime 28mm T1.3",
    lighting: "Sunset Amber Rim Light",
    characters: ["The Final Breath"],
    actionDescription: "Cinematic 4K intimate low-light shot in island bedroom May 1821, dying emperor on simple campaign cot, candlelight flickering out as lips whisper final words in deep peace, 24fps cinematic finale",
    soundCue: "Chamber Cello & Foley"
  },
];

export const NAPOLEON_ROMANCE_DIALOGUES: FeatureFilmDialogue[] = [
  {
    id: "nap_dia_01",
    actNumber: 1,
    character: "Young Napoleon Bonaparte",
    actorRole: "Artillery Officer (25 years old)",
    timestampSec: 2,
    timecodeFormatted: "00:02",
    emotion: "Passionate Ardor",
    text: {
      fr: "Regardez, mademoiselle... Il n'y a pas de plus belle vue dans toute la Provence à cette heure.",
      en: "Look, mademoiselle... There is no finer view in all of Provence at this hour.",
      hi: "देखिए, मादामुआजेल... इस पहर पूरे प्रोवेंस में इससे सुंदर दृश्य कोई नहीं है।",
      es: "Mire, señorita... No hay vista más hermosa en toda la Provenza a esta hora.",
      it: "Guardate, signorina... Non c'è vista più bella in tutta la Provenza a quest'ora.",
      ja: "ご覧なさい、お嬢さん…この時刻のプロヴァンスにはこれ以上の絶景はありません。"
    }
  },
  {
    id: "nap_dia_02",
    actNumber: 1,
    character: "Désirée Clary",
    actorRole: "First Love (Marseille Merchant's Daughter)",
    timestampSec: 8,
    timecodeFormatted: "00:08",
    emotion: "Gentle Affection & Trepidation",
    text: {
      fr: "Vous parlez de gloire comme si elle pouvait réchauffer un cœur solitaire, Napoléon.",
      en: "You speak of glory as if it could warm a lonely heart, Napoleon.",
      hi: "आप गौरव की बात ऐसे करते हैं, नेपोलियन, मानो वह किसी अकेले हृदय को गर्माहट दे सके।",
      es: "Hablas de gloria como si pudiera calentar un corazón solitario, Napoleón.",
      it: "Parli di gloria come se potesse scaldare un cuore solitario, Napoleone.",
      ja: "ナポレオン、まるで栄光が孤独な心を温めてくれるかのように話すのですね。"
    }
  },
  {
    id: "nap_dia_03",
    actNumber: 2,
    character: "Empress Joséphine",
    actorRole: "Empress of the French",
    timestampSec: 42,
    timecodeFormatted: "00:42",
    emotion: "Heartfelt Melancholy & Nobility",
    text: {
      fr: "Mon cher Bonaparte, vous avez couronné une femme dont l'âme vous appartiendra toujours, au-delà de toute couronne.",
      en: "My dear Bonaparte, you crowned a woman whose soul will always belong to you, beyond all crowns.",
      hi: "मेरे प्रिय बोनापार्ट, आपने उस स्त्री को ताज पहनाया है जिसकी आत्मा हर ताज से परे सदा आपकी ही रहेगी।",
      es: "Mi querido Bonaparte, coronaste a una mujer cuya alma siempre te pertenecerá, más allá de toda corona.",
      it: "Mio caro Bonaparte, hai incoronato una donna la cui anima ti apparterrà per sempre, al di là di ogni corona.",
      ja: "愛するボナパルト、あなたはどんな王冠をも超えて、その魂が永遠にあなたのものとなる女性に冠を授けたのです。"
    }
  },
  {
    id: "nap_dia_04",
    actNumber: 3,
    character: "Countess Marie Walewska",
    actorRole: "The Polish Patriot",
    timestampSec: 78,
    timecodeFormatted: "01:18",
    emotion: "Devotion & Sorrow",
    text: {
      fr: "Au milieu de cet hiver cruel, votre tendresse est le seul feu qui ne s'éteint pas.",
      en: "In the midst of this cruel winter, your tenderness is the only fire that never dies.",
      hi: "इस कठोर शीतकाल में, आपकी कोमलता ही वह एकमात्र अग्नि है जो कभी बुझती नहीं।",
      es: "En medio de este invierno cruel, tu ternura es el único fuego que nunca se apaga.",
      it: "Nel mezzo di questo crudele inverno, la tua tenerezza è l'unico fuoco che non si spegne mai.",
      ja: "この残酷な冬のただ中で、あなたの優しさだけが消えることのない唯一の炎です。"
    }
  },
  {
    id: "nap_dia_05",
    actNumber: 4,
    character: "Napoleon Bonaparte",
    actorRole: "The Emperor",
    timestampSec: 114,
    timecodeFormatted: "01:54",
    emotion: "Tormented Duty",
    text: {
      fr: "La France réclame un héritier, mais mon cœur réclamera toujours Joséphine.",
      en: "France demands an heir, but my heart will forever demand Joséphine.",
      hi: "फ्रांस को एक उत्तराधिकारी चाहिए, किंतु मेरा हृदय सदा जोसेफिन को ही चाहेगा।",
      es: "Francia exige un heredero, pero mi corazón siempre exigirá a Josefina.",
      it: "La Francia esige un erede, ma il mio cuore esigerà per sempre Giuseppina.",
      ja: "フランスは後継者を求めているが、私の心は永遠にジョゼフィーヌを求め続けるだろう。"
    }
  },
  {
    id: "nap_dia_06",
    actNumber: 5,
    character: "Napoleon on Saint Helena",
    actorRole: "Exiled Emperor",
    timestampSec: 150,
    timecodeFormatted: "02:30",
    emotion: "Last Words & Transcendent Reverie",
    text: {
      fr: "France... armée... tête d'armée... Joséphine.",
      en: "France... army... head of the army... Joséphine.",
      hi: "फ्रांस... सेना... सेना का अग्रभाग... जोसेफिन।",
      es: "Francia... ejército... cabeza de ejército... Josefina.",
      it: "Francia... esercito... capo dell'esercito... Giuseppina.",
      ja: "フランス…軍隊…軍の先頭…ジョゼフィーヌ。"
    }
  }
];
