steps:
  # 1. Build container image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zyvoriq:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zyvoriq:latest'
      - '.'

  # 2. Push container image to GCR / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/zyvoriq'

  # 3. Deploy to Cloud Run (routed via cr-infra-dynamic-url-cr-neg -> https://zyvoriq-887605034827.cr.gclb.goog)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zyvoriq'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zyvoriq:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--ingress'
      - 'internal-and-cloud-load-balancing'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'

images:
  - 'gcr.io/$PROJECT_ID/zyvoriq:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/zyvoriq:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s

