import { ExecutivePersona } from "./types";

export const EXECUTIVE_PERSONAS: ExecutivePersona[] = [
  {
    id: "priya",
    name: "Priya Sharma",
    title: "Global Transformation CTO",
    location: "Bangalore, India",
    gender: "female",
    avatarUrl: "/assets/avatars/priya.jpg",
    videoUrl: "/assets/video/veo_priya_24s_master.mp4",
    audioUrl: "/assets/audio/priya.wav",
    accent: "Indian English (Executive Orator)",
    voiceStyle: "Authoritative, Visionary & Energetic",
    defaultScript: "Hello everyone! I'm Priya, Global Transformation CTO. Traditional enterprise content pipelines take 14 long days and over $140,000. With Zyvoriq, we collapse that entire lifecycle into just 90 seconds—backed by Veritas cryptographic consensus and Ed25519 provenance!",
    bio: "Priya leads global enterprise architecture and AI deployment across Tier-1 financial institutions and cloud hyperscalers.",
    c2paCertId: "C2PA-ED25519-PRIYA-8849-VERITAS"
  },
  {
    id: "victoria",
    name: "Victoria Sterling",
    title: "MasterClass Executive VP",
    location: "London, UK",
    gender: "female",
    avatarUrl: "/assets/avatars/victoria.jpg",
    videoUrl: "",
    audioUrl: "/assets/audio/victoria.wav",
    accent: "British Received Pronunciation",
    voiceStyle: "Polished, Articulate & Prestigious",
    defaultScript: "Welcome, distinguished colleagues. Today, we redefine executive sovereign governance. Every asset produced within our enclave carries immutable Ed25519 cryptographic signatures and absolute audit consensus.",
    bio: "Victoria directs sovereign enterprise media architecture and Fortune 100 executive keynote production.",
    c2paCertId: "C2PA-ED25519-VICTORIA-4402-VERITAS"
  },
  {
    id: "david",
    name: "David Vance",
    title: "Chief Security Officer",
    location: "New York, USA",
    gender: "male",
    avatarUrl: "/assets/avatars/david.jpg",
    videoUrl: "",
    audioUrl: "/assets/audio/david.wav",
    accent: "North American General",
    voiceStyle: "Commanding, Methodical & Deep",
    defaultScript: "Security is non-negotiable. At Zyvoriq, our cryptographic seals are anchored directly to hardware enclave security modules, ensuring zero tampering across the entire enterprise broadcast supply chain.",
    bio: "David specializes in zero-trust media provenance, zero-knowledge proofs, and sovereign cryptographic consensus.",
    c2paCertId: "C2PA-ED25519-DAVID-1193-VERITAS"
  },
  {
    id: "elena",
    name: "Elena Rostova",
    title: "Global VP of Product Strategy",
    location: "Zurich, Switzerland",
    gender: "female",
    avatarUrl: "/assets/avatars/elena.jpg",
    videoUrl: "",
    audioUrl: "/assets/audio/elena.wav",
    accent: "Continental European (Multilingual Orator)",
    voiceStyle: "Dynamic, Sophisticated & Inspiring",
    defaultScript: "Transforming enterprise agility requires eliminating friction. With Zyvoriq, our teams produce broadcast-quality media in seconds, with complete cryptographic consensus and zero compliance overhead.",
    bio: "Elena leads international product strategy and enterprise AI transformation for global conglomerates.",
    c2paCertId: "C2PA-ED25519-ELENA-7731-VERITAS"
  },
  {
    id: "jonathan",
    name: "Jonathan Mercer",
    title: "Chief AI Systems Architect",
    location: "San Francisco, USA",
    gender: "male",
    avatarUrl: "/assets/avatars/jonathan.jpg",
    videoUrl: "",
    audioUrl: "/assets/audio/jonathan.wav",
    accent: "West Coast Tech Executive",
    voiceStyle: "Innovative, Precise & Energetic",
    defaultScript: "By combining low-latency neural synthesis with mathematical provenance proofs, we have created the world's first truly sovereign media platform for modern hyperscale enterprises.",
    bio: "Jonathan architects low-latency neural video pipelines, diffusion models, and real-time distributed consensus engines.",
    c2paCertId: "C2PA-ED25519-JONATHAN-6624-VERITAS"
  },
  {
    id: "maya",
    name: "Maya Lin",
    title: "VP of Enterprise Governance",
    location: "Singapore",
    gender: "female",
    avatarUrl: "/assets/avatars/maya.jpg",
    videoUrl: "",
    audioUrl: "/assets/audio/maya.wav",
    accent: "Singaporean / International English",
    voiceStyle: "Clear, Reassuring & Authoritative",
    defaultScript: "Governance and speed must coexist. Zyvoriq provides mathematical certainty for every pixel rendered, allowing regulated enterprises to communicate with total confidence and velocity.",
    bio: "Maya oversees regulatory compliance, C2PA standards adoption, and AI safety frameworks across Asia-Pacific.",
    c2paCertId: "C2PA-ED25519-MAYA-3398-VERITAS"
  }
];
