import { ExecutivePersona } from "./types";

export const EXECUTIVE_PERSONAS: ExecutivePersona[] = [
  {
    id: "priya",
    name: "Priya Sharma",
    title: "Global Transformation CTO",
    location: "Bangalore, India",
    gender: "female",
    avatarUrl: "/assets/avatars/priya.jpg",
    videoUrl: "/assets/video/veo_priya_master.mp4",
    audioUrl: "/assets/audio/priya.wav",
    accent: "Indian English (Executive Orator)",
    voiceStyle: "Authoritative, Visionary & Energetic",
    defaultScript: "Hello everyone! I'm Priya, Global Transformation CTO. Traditional enterprise content pipelines take 14 long days and over $140,000. With Zyvoriq, we collapse that entire lifecycle into just 90 seconds!",
    bio: "Priya leads global enterprise architecture and AI deployment across Tier-1 financial institutions and cloud hyperscalers.",
    c2paCertId: "C2PA-ED25519-PRIYA-8849-VERITAS"
  },
  {
    id: "victoria",
    name: "Victoria Sterling",
    title: "MasterClass Executive VP",
    location: "London, UK",
    gender: "female",
    avatarUrl: "/assets/avatars/victoria.jpg",
    videoUrl: "/assets/video/victoria_master.mp4",
    audioUrl: "/assets/audio/victoria.wav",
    accent: "British RP (Aristocratic Gravitas)",
    voiceStyle: "Poised, Eloquent & Measured",
    defaultScript: "Good day, executives. In a world saturated with synthetic hallucinations, verifiable truth is the ultimate enterprise currency. Zyvoriq delivers immutable governance for the autonomous generative era.",
    bio: "Former FTSE-100 Chief Risk Officer, now directing autonomous governance frameworks for sovereign wealth funds.",
    c2paCertId: "C2PA-ED25519-VICTORIA-3910-VERITAS"
  },
  {
    id: "david",
    name: "David Vance",
    title: "Visionary Tech Orator & Founder",
    location: "San Francisco, CA",
    gender: "male",
    avatarUrl: "/assets/avatars/david.jpg",
    videoUrl: "/assets/video/david_master.mp4",
    audioUrl: "/assets/audio/david.wav",
    accent: "US West Coast Tech Orator",
    voiceStyle: "High-Paced, Compelling & Disruptive",
    defaultScript: "We are at the inflection point of human intelligence. With Zyvoriq, every corporate briefing, every board keynote, and every multi-agent workflow is rendered with zero latency and absolute cryptographic certainty.",
    bio: "Serial AI entrepreneur and keynote speaker specializing in frontier foundational models and autonomous swarm orchestration.",
    c2paCertId: "C2PA-ED25519-DAVID-1120-VERITAS"
  },
  {
    id: "elena",
    name: "Dr. Elena Rostova",
    title: "AI Tech Founder & Lead",
    location: "Berlin, Germany",
    gender: "female",
    avatarUrl: "/assets/avatars/elena.jpg",
    videoUrl: "/assets/video/elena_master.mp4",
    audioUrl: "/assets/audio/elena.wav",
    accent: "European English (Precision Engineering)",
    voiceStyle: "Analytical, Sharp & Confident",
    defaultScript: "Precision is non-negotiable in mission-critical infrastructure. Zyvoriq combines sub-millisecond audio-visual latency with deterministic mathematical alignment across all production viewports.",
    bio: "Deep-tech roboticist and neural rendering researcher pioneering high-throughput synthetic pipelines.",
    c2paCertId: "C2PA-ED25519-ELENA-5521-VERITAS"
  },
  {
    id: "maya",
    name: "Maya O'Connor",
    title: "Intimate Fireside Novelist",
    location: "Dublin, Ireland",
    gender: "female",
    avatarUrl: "/assets/avatars/maya.jpg",
    videoUrl: "/assets/video/maya_master.mp4",
    audioUrl: "/assets/audio/maya.wav",
    accent: "Warm Irish Lilt",
    voiceStyle: "Empathetic, Narrative & Engaging",
    defaultScript: "Every enterprise transformation begins with a compelling story. Let me show you how Zyvoriq turns complex operational data into captivating, humanized executive narratives in real time.",
    bio: "Executive narrative director translating complex quantitative telemetry into inspiring stakeholder briefings.",
    c2paCertId: "C2PA-ED25519-MAYA-7782-VERITAS"
  },
  {
    id: "jonathan",
    name: "Sir Jonathan Reynolds",
    title: "DeepMind Documentary Baritone",
    location: "Oxford, UK",
    gender: "male",
    avatarUrl: "/assets/avatars/jonathan.jpg",
    videoUrl: "/assets/video/jonathan_master.mp4",
    audioUrl: "/assets/audio/jonathan.wav",
    accent: "BBC Master Orator",
    voiceStyle: "Resonant, Cinematic & Deep",
    defaultScript: "Witness the convergence of generative intelligence and cryptographic consensus. A new standard for executive digital identity, authenticated across every frame of reality.",
    bio: "Veteran scientific broadcaster and institutional historian narrating the dawn of sovereign artificial intelligence.",
    c2paCertId: "C2PA-ED25519-JONATHAN-9943-VERITAS"
  }
];
